import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google"
import "./globals.css";
import Header from "./components/Header";
import Head from 'next/head';
import { Toaster } from "react-hot-toast";

const pop = Poppins({ subsets: ["latin"], weight: '400' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/_next/static/css/app/layout.css"
          as="style"
          onLoad={() => {
            const link = document.querySelector('link[rel="preload"]') as HTMLLinkElement;
            if (link) {
              link.onload = null;
              link.rel = 'stylesheet';
            }
          }}
        />
      </Head>
      <body
        className={`${pop.className} antialiased`}
      >
        <Header />
        {children}
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
