import type { Metadata } from "next";
import { Poppins } from "next/font/google"
import "./globals.css";
import Header from "./components/Header";
import Head from 'next/head';
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./context/AuthContext";
import { auth } from "@/auth";

const pop = Poppins({ subsets: ["latin"], weight: '400' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user

  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          href="/_next/static/css/app/layout.css"
          as="style"
          onLoad={() => {
            const link = document.querySelector('link[rel="preload"]') as HTMLLinkElement;
            if (link) {
              link.onload = null;
              link.rel = 'stylesheet';
            }
          }}
        />
      </Head>
      <body
        className={`${pop.className} antialiased`}
      >
        <AuthProvider>
          <Header user={user} />
          {children}
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
